config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :areas, only: [:index, :show] do
    resources :breweries, only: [:new, :create]
  end

  resources :breweries, only: [:index, :show] do
    resources :brands, only: [:new, :create]
  end
  
  resources :brands, only: [:index, :show] do
    collection do
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    {id: 0, name: "その他"},
    {id: 1, name: "北海道"},
    {id: 2, name: "青森県"},
    {id: 3, name: "岩手県"},
    {id: 4, name: "宮城県"},
    {id: 5, name: "秋田県"},
    {id: 6, name: "山形県"},
    {id: 7, name: "福島県"},
    {id: 8, name: "茨城県"},
    {id: 9, name: "栃木県"},
    {id: 10, name: "群馬県"},
    {id: 11, name: "埼玉県"},
    {id: 12, name: "千葉県"},
    {id: 13, name: "東京都"},
    {id: 14, name: "神奈川県"},
    {id: 15, name: "新潟県"},
    {id: 16, name: "富山県"},
    {id: 17, name: "石川県"},
    {id: 18, name: "福井県"},
    {id: 19, name: "山梨県"},
    {id: 20, name: "長野県"},
    {id: 21, name: "岐阜県"},
    {id: 22, name: "静岡県"},
    {id: 23, name: "愛知県"},
    {id: 24, name: "三重県"},
    {id: 25, name: "滋賀県"},
    {id: 26, name: "京都府"},
    {id: 27, name: "大阪府"},
    {id: 28, name: "兵庫県"},
    {id: 29, name: "奈良県"},
    {id: 30, name: "和歌山県"},
    {id: 31, name: "鳥取県"},
    {id: 32, name: "島根県"},
    {id: 33, name: "岡山県"},
    {id: 34, name: "広島県"},
    {id: 35, name: "山口県"},
    {id: 36, name: "徳島県"},
    {id: 37, name: "香川県"},
    {id: 38, name: "愛媛県"},
    {id: 39, name: "高知県"},
    {id: 40, name: "福岡県"},
    {id: 41, name: "佐賀県"},
    {id: 42, name: "長崎県"},
    {id: 43, name: "熊本県"},
    {id: 44, name: "大分県"},
    {id: 45, name: "宮崎県"},
    {id: 46, name: "鹿児島県"},
    {id: 47, name: "沖縄県"}
  ]
  include ActiveHash::Associations
  has_many :breweries
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_user

  def index
    @areas = Area.all
  end

  def show
    @area = Area.find(params[:id])
    @breweries = @area.breweries
  end

  private
  def set_user
    @user = current_user
  end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/index.html.erb
<div class="areas-container">
  <h2>蔵元の所在地を選択してください</h2>
  <div class="area-container 1">
    <h3>北海道・東北地方</h3>
    <% Area.where(id: 1..7).each do |area| %>
      <%= link_to area.name, area_path(area), class: "area-select" %>
    <% end %>
  </div>
  <div class="area-container 2">
    <h3>関東地方</h3>
    <% Area.where(id: 8..14).each do |area| %>
      <%= link_to area.name, area_path(area), class: "area-select" %>
    <% end %>
  </div>
  <div class="area-container 3">
    <h3>中部地方</h3>
    <% Area.where(id: 15..23).each do |area| %>
      <%= link_to area.name, area_path(area), class: "area-select" %>
    <% end %>
  </div>
  <div class="area-container 4">
    <h3>関西地方</h3>
    <% Area.where(id: 24..30).each do |area| %>
      <%= link_to area.name, area_path(area), class: "area-select" %>
    <% end %>
  </div>
  <div class="area-container 5">
    <h3>中国地方</h3>
      <% Area.where(id: 31..35).each do |area| %>
        <%= link_to area.name, area_path(area), class: "area-select" %>
      <% end %>
  </div>
  <div class="area-container 6">
    <h3>四国地方</h3>
      <% Area.where(id: 36..39).each do |area| %>
        <%= link_to area.name, area_path(area), class: "area-select" %>
      <% end %>
  </div>
  <div class="area-container 7">
    <h3>九州・沖縄地方</h3>
      <% Area.where(id: 40..47).each do |area| %>
        <%= link_to area.name, area_path(area), class: "area-select" %>
      <% end %>
  </div>
  <div class="area-container 8">
    <h3>その他</h3>
      <% Area.where(id: 0).each do |area| %>
        <%= link_to area.name, area_path(area), class: "area-select" %>
      <% end %>
  </div>
</div>

app/views/areas/show.html.erb
<div class="brewerys-container">
  <h2><%= "#{@area.name}の蔵元一覧" %></h2>
  <%= link_to '蔵元登録', new_area_brewery_path(@area) %>
  <%= link_to '地域検索へ戻る', areas_path %>
  <div class="brewery-container">
    <% @breweries.each do |brewery| %>
      <div class="brewery-select">
        <%= link_to brewery.name, brewery_path(brewery) %>
      </div>
    <% end %>
  </div>
</div>