config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :areas, only: [:index, :show] do
    resources :breweries, only: [:new, :create]
  end

  resources :breweries, only: [:index, :show] do
    resources :brands, only: [:new, :create]
  end
  
  resources :brands, only: [:index, :show] do
    collection do
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :area_id
  end
  
  has_many :brands

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]
  def show
    @brewery = Brewery.find(params[:id])
    @brands = @brewery.brands
  end

  def new
    @area = Area.find(params[:area_id])
    @brewery = Brewery.new
  end

  def create
    @area = Area.find(params[:area_id])
    @brewery = Brewery.new(brewery_params)
    if @brewery.save
      redirect_to action: :show, id: @brewery
    else
      render :new
    end
  end

  private
  def brewery_params
    params.require(:brewery).permit(:name).merge(area_id: @area.id)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/new.html.erb
<div class="brewery-container">
  <h2>蔵元登録</h2>
  <h3><%= @area.name %></h3>


  <%= form_with model: [@area, @brewery], local: true do |f| %>
    <%# <%= render "devise/shared/error_messages", resource: resource %>

    <div class="brewery-field">
      <%= f.label :name, "蔵元名" %><br>
      <%= f.text_field :name, autocomplete: '蔵元', autofocus: true %>
    </div>

    <div class="brewery-actions">
      <%= f.submit "追加" %>
    </div>
  <% end %>
  <%= link_to '戻る', area_path(@area) %>
</div>

app/views/breweries/show.html.erb
<div class="brands-container">
  <h2><%= "#{@brewery.name}の銘柄一覧" %></h2>
  <%= link_to '銘柄登録', new_brewery_brand_path(@brewery) %>
  <%= link_to "#{@brewery.area.name}の蔵元一覧へ戻る", area_path(@brewery.area_id) %>
  <div class="brand-container">
    <% @brands.each do |brand| %>
      <div class="brand-select">
        <%= link_to brand.name, brand_path(brand) %><br>
        <% if brand.aroma.nil? %>
          未評価<br>
        <% else %>
          香り:<%= brand.aroma %>
          第一印象:<%= brand.impression %>
          旨味:<%= brand.taste %>
          余韻:<%= brand.afterglow %><br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>