config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :areas, only: [:index, :show] do
    resources :breweries, only: [:new, :create]
  end

  resources :breweries, only: [:index, :show] do
    resources :brands, only: [:new, :create]
  end
  
  resources :brands, only: [:index, :show] do
    collection do
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/brand.rb
class Brand < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :brewery_id
  end
  
  belongs_to :brewery
  has_many :reviews
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  def show
    @brand = Brand.find(params[:id])
    @reviews = @brand.reviews.order(updated_at: "DESC")
  end

  def new
    @brewery = Brewery.find(params[:brewery_id])
    @brand = Brand.new
  end

  def create
    @brewery = Brewery.find(params[:brewery_id])
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to action: :show, id: @brand
    else
      render :new
    end
  end

  def search
    @brands = SearchBrandsService.search(params[:keyword])
  end

  private
  def brand_params
    params.require(:brand).permit(:name).merge(brewery_id: @brewery.id)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/new.html.erb
<div class="brand-container">
  <h2>銘柄登録</h2>
  <h3><%= @brewery.name %></h3>


  <%= form_with model: [@brewery, @brand], local: true do |f| %>
    <%# <%= render "devise/shared/error_messages", resource: resource %>

    <div class="brand-field">
      <%= f.label :name, "銘柄名" %><br>
      <%= f.text_field :name, autocomplete: '銘柄', autofocus: true %>
    </div>

    <div class="brand-actions">
      <%= f.submit "追加" %>
    </div>
  <% end %>
  <%= link_to '戻る', brewery_path(@brewery) %>
</div>

app/views/brands/search.html.erb
<div class="contents row">
  <% @brands.each do |brand| %>
    <%= brand.name %>
  <% end %>
</div>

app/views/brands/show.html.erb
<div class="selections">
  <h2><%= @brand.name %></h2>
  <h3>味わい</h3>
  <% if @brand.aroma.nil? %>
    評価がありません<br>
  <% else %>
    香り:<%= @brand.aroma %>
    第一印象:<%= @brand.impression %>
    旨味:<%= @brand.taste %>
    余韻:<%= @brand.afterglow %><br>
  <% end %>
  <%= link_to 'レビュー投稿', new_brand_review_path(@brand) %>
  <%= link_to "#{@brand.brewery.name}の銘柄一覧へ戻る", brewery_path(@brand.brewery_id) %>

  <h3>レビュー一覧</h3>
  <div class="reviews-container">
    <% @reviews.each do |review| %>
      <div class="review-container">
        <%= link_to review.user.nickname, user_path(review.user) %><br>
        <%= image_tag review.image.variant(resize: '450x450'), class: 'review-image' if review.image.attached? %><br>
        香り:<%= review.aroma_id %>
        第一印象:<%= review.impression_id %>
        旨味:<%= review.taste_id %>
        余韻:<%= review.afterglow_id %><br>
        コメント:<%= review.comment %><br>
      </div>
    <% end %>
  </div>
</div>