config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :areas, only: [:index, :show] do
    resources :breweries, only: [:new, :create]
  end

  resources :breweries, only: [:index, :show] do
    resources :brands, only: [:new, :create]
  end
  
  resources :brands, only: [:index, :show] do
    collection do
      get :search
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/afterglow.rb
class Afterglow < ActiveHash::Base
  self.data = [
    { id: 0, name: '短い' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
    { id: 4, name: 4 },
    { id: 5, name: 5 },
    { id: 6, name: 6 },
    { id: 7, name: 7 },
    { id: 8, name: 8 },
    { id: 9, name: 9 },
    { id: 10, name: '長い' }
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    {id: 0, name: "その他"},
    {id: 1, name: "北海道"},
    {id: 2, name: "青森県"},
    {id: 3, name: "岩手県"},
    {id: 4, name: "宮城県"},
    {id: 5, name: "秋田県"},
    {id: 6, name: "山形県"},
    {id: 7, name: "福島県"},
    {id: 8, name: "茨城県"},
    {id: 9, name: "栃木県"},
    {id: 10, name: "群馬県"},
    {id: 11, name: "埼玉県"},
    {id: 12, name: "千葉県"},
    {id: 13, name: "東京都"},
    {id: 14, name: "神奈川県"},
    {id: 15, name: "新潟県"},
    {id: 16, name: "富山県"},
    {id: 17, name: "石川県"},
    {id: 18, name: "福井県"},
    {id: 19, name: "山梨県"},
    {id: 20, name: "長野県"},
    {id: 21, name: "岐阜県"},
    {id: 22, name: "静岡県"},
    {id: 23, name: "愛知県"},
    {id: 24, name: "三重県"},
    {id: 25, name: "滋賀県"},
    {id: 26, name: "京都府"},
    {id: 27, name: "大阪府"},
    {id: 28, name: "兵庫県"},
    {id: 29, name: "奈良県"},
    {id: 30, name: "和歌山県"},
    {id: 31, name: "鳥取県"},
    {id: 32, name: "島根県"},
    {id: 33, name: "岡山県"},
    {id: 34, name: "広島県"},
    {id: 35, name: "山口県"},
    {id: 36, name: "徳島県"},
    {id: 37, name: "香川県"},
    {id: 38, name: "愛媛県"},
    {id: 39, name: "高知県"},
    {id: 40, name: "福岡県"},
    {id: 41, name: "佐賀県"},
    {id: 42, name: "長崎県"},
    {id: 43, name: "熊本県"},
    {id: 44, name: "大分県"},
    {id: 45, name: "宮崎県"},
    {id: 46, name: "鹿児島県"},
    {id: 47, name: "沖縄県"}
  ]
  include ActiveHash::Associations
  has_many :breweries
end

app/models/aroma.rb
class Aroma < ActiveHash::Base
  self.data = [
    { id: 0, name: '穏やか' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
    { id: 4, name: 4 },
    { id: 5, name: 5 },
    { id: 6, name: 6 },
    { id: 7, name: 7 },
    { id: 8, name: 8 },
    { id: 9, name: 9 },
    { id: 10, name: '華やか' }
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :reviews
end

app/models/brand.rb
class Brand < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :brewery_id
  end
  
  belongs_to :brewery
  has_many :reviews
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :area_id
  end
  
  has_many :brands

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
end

app/models/impression.rb
class Impression < ActiveHash::Base
  self.data = [
    { id: 0, name: '優しい' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
    { id: 4, name: 4 },
    { id: 5, name: 5 },
    { id: 6, name: 6 },
    { id: 7, name: 7 },
    { id: 8, name: 8 },
    { id: 9, name: 9 },
    { id: 10, name: 'しっかり' }
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  with_options numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9} do
    validates :aroma_id
    validates :impression_id
    validates :taste_id
    validates :afterglow_id
  end

  belongs_to :user
  belongs_to :brand
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :aroma
  belongs_to :impression
  belongs_to :taste
  belongs_to :afterglow

end

app/models/taste.rb
class Taste < ActiveHash::Base
  self.data = [
    { id: 0, name: '軽快' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
    { id: 4, name: 4 },
    { id: 5, name: 5 },
    { id: 6, name: 6 },
    { id: 7, name: 7 },
    { id: 8, name: 8 },
    { id: 9, name: 9 },
    { id: 10, name: '芳醇' }
  ]

  include ActiveHash::Associations
  has_many :users
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true

  with_options numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9} do
    validates :aroma_id
    validates :impression_id
    validates :taste_id
    validates :afterglow_id
  end

  has_many :reviews

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :aroma
  belongs_to :impression
  belongs_to :taste
  belongs_to :afterglow
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_user

  def index
    @areas = Area.all
  end

  def show
    @area = Area.find(params[:id])
    @breweries = @area.breweries
  end

  private
  def set_user
    @user = current_user
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  def show
    @brand = Brand.find(params[:id])
    @reviews = @brand.reviews.order(updated_at: "DESC")
  end

  def new
    @brewery = Brewery.find(params[:brewery_id])
    @brand = Brand.new
  end

  def create
    @brewery = Brewery.find(params[:brewery_id])
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to action: :show, id: @brand
    else
      render :new
    end
  end

  def search
    @brands = SearchBrandsService.search(params[:keyword])
  end

  private
  def brand_params
    params.require(:brand).permit(:name).merge(brewery_id: @brewery.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_brand, only: [:new, :create]
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @reviews = Review.includes(:user).order("updated_at DESC").limit(15)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to controller: :brands, action: :show, id: params[:brand_id]
      aroma = Review.where(brand_id: @brand.id).average(:aroma_id)
      impression = Review.where(brand_id: @brand.id).average(:impression_id)
      taste = Review.where(brand_id: @brand.id).average(:taste_id)
      afterglow = Review.where(brand_id: @brand.id).average(:afterglow_id)
      Brand.where(id: @brand.id).update(aroma: aroma, impression: impression, taste: taste, afterglow: afterglow)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:aroma_id, :impression_id, :taste_id, :afterglow_id, :comment, :image).merge(user_id: current_user.id, brand_id: params[:brand_id])
  end

  def set_brand
    @brand = Brand.find(params[:brand_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = current_user.reviews.limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nonbay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="header-content">
        <div class="left-content">
          <%= link_to image_tag('sugidama.png', size: "60x60"), root_path, class: "header-img" %>
          <%= link_to 'のんべぇ', root_path, class: "title" %>
          <%= link_to '地域検索', areas_path, class: "brand-search" %>
          <%= link_to '味わい検索', "#", class: "feature-search" %>
        </div>
        <div class="center-content">
          <form>
            <%= form_with(url: search_brands_path, local: true, method: :get, class: "search-form") do |f| %>
              <%= f.text_field :keyword, placeholder: "銘柄検索", class: "search-input" %>
              <%# <%= f.submit "検索", class: "search-btn" %>
            <% end %>
          </form>
        </div>
        <div class="right-content">
          <% if user_signed_in? %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :DELETE, class: "logout" %>
          <% else %>
            <%= link_to 'ログイン', new_user_session_path, class: "login" %>
            <%= link_to '新規登録', new_user_registration_path, class: "signup" %>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <% if user_signed_in? && current_page?(root_path) %>
        <div class="top-main-wrapper">
          <div class="top-main-container">
            <%= yield %>
          </div>
        </div>
        <div class="side-menu">
          <%= render "shared/mypage" %>
        </div>
      <% elsif current_page?(root_path) %>
        <div class="guest-main-wrapper">
          <div class="guest-main-container">
            <%= yield %>
          </div>
        </div>
      <% else %>
        <div class="main-wrapper">
          <div class="main-container">
            <%= yield %>
          </div>
        </div>
      <% end %>
    </main>
  </body>
</html>

app/views/shared/_mypage.html.erb
<div class="mypage-content">
  <div class="mypage-title">
    <h2><%= link_to current_user.nickname, user_path(current_user) %></h2>
  </div>
  <div class="favorites-container">
    <%= link_to 'お気に入りの銘柄', '#' %>
  </div>
  <h3>好みの味わい</h3>
  <div class="mypage-like">
    香り:<%= current_user.aroma_id %>
    第一印象:<%= current_user.impression_id %>
    旨味:<%= current_user.taste_id %>
    余韻:<%= current_user.afterglow_id %>
  </div>
  <div class="recomends-container">
    <h3>おすすめの銘柄</h3>
    <% @recomends.each do |recomend| %>
      <div class="recomend-container">
        <%= link_to recomend.brewery.name, brewery_path(recomend.brewery) %> / <%= link_to recomend.name, brand_path(recomend) %><br>
        香り:<%= recomend.aroma %>
        第一印象:<%= recomend.impression %>
        旨味:<%= recomend.taste %>
        余韻:<%= recomend.afterglow %><br>
      </div>
    <% end %>
  </div>
  <div class="myreviews-container">
    <h3>最近投稿したレビュー</h3>
    <% current_user.reviews.each do |review| %>
      <div class="myreview-container">
        <%= link_to review.brand.brewery.name, brewery_path(review.brand.brewery) %> / <%= link_to review.brand.name, brand_path(review.brand) %><br>
        香り:<%= review.aroma_id %>
        第一印象:<%= review.impression_id %>
        旨味:<%= review.taste_id %>
        余韻:<%= review.afterglow_id %><br>
        コメント:<%= review.comment %>
      </div>
    <% end %>
    <div class="api-link">
      本アプリケーションは<a href="https://sakenowa.com">さけのわデータ</a>を利用しています
    </div>
  </div>
</div>